// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnAyOetEQeT3F_abNGP350gxIsB-aJldw',
    appId: '1:843981630732:web:490e615c7fc2c719eb6d29',
    messagingSenderId: '843981630732',
    projectId: 'juinstagaram',
    authDomain: 'juinstagaram.firebaseapp.com',
    storageBucket: 'juinstagaram.appspot.com',
    measurementId: 'G-52CKT3LL4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChIzclcKF2G0rrqVdBm8WN6NJNsKOd_g8',
    appId: '1:843981630732:android:3241ae21b5a7bac9eb6d29',
    messagingSenderId: '843981630732',
    projectId: 'juinstagaram',
    storageBucket: 'juinstagaram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxUDk3WvLAzL_pSUJn_gLS_NwcHJekmw',
    appId: '1:843981630732:ios:3da9ee3dd139b106eb6d29',
    messagingSenderId: '843981630732',
    projectId: 'juinstagaram',
    storageBucket: 'juinstagaram.appspot.com',
    iosBundleId: 'com.example.juinstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxUDk3WvLAzL_pSUJn_gLS_NwcHJekmw',
    appId: '1:843981630732:ios:3da9ee3dd139b106eb6d29',
    messagingSenderId: '843981630732',
    projectId: 'juinstagaram',
    storageBucket: 'juinstagaram.appspot.com',
    iosBundleId: 'com.example.juinstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnAyOetEQeT3F_abNGP350gxIsB-aJldw',
    appId: '1:843981630732:web:216ba0333112c835eb6d29',
    messagingSenderId: '843981630732',
    projectId: 'juinstagaram',
    authDomain: 'juinstagaram.firebaseapp.com',
    storageBucket: 'juinstagaram.appspot.com',
    measurementId: 'G-FK3YZY7GQR',
  );
}
